// Code generated by "stringer -type=OutputFlag"; DO NOT EDIT.

package termios

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPOST-1]
	_ = x[OLCUC-2]
	_ = x[ONLCR-4]
	_ = x[OCRNL-8]
	_ = x[ONOCR-16]
	_ = x[ONLRET-32]
	_ = x[OFILL-64]
	_ = x[OFDEL-128]
	_ = x[NLDLY-256]
	_ = x[CRDLY-1536]
	_ = x[TABDLY-6144]
	_ = x[BSDLY-8192]
	_ = x[VTDLY-16384]
	_ = x[FFDLY-32768]
}

const _OutputFlag_name = "OPOSTOLCUCONLCROCRNLONOCRONLRETOFILLOFDELNLDLYCRDLYTABDLYBSDLYVTDLYFFDLY"

var _OutputFlag_map = map[OutputFlag]string{
	1:     _OutputFlag_name[0:5],
	2:     _OutputFlag_name[5:10],
	4:     _OutputFlag_name[10:15],
	8:     _OutputFlag_name[15:20],
	16:    _OutputFlag_name[20:25],
	32:    _OutputFlag_name[25:31],
	64:    _OutputFlag_name[31:36],
	128:   _OutputFlag_name[36:41],
	256:   _OutputFlag_name[41:46],
	1536:  _OutputFlag_name[46:51],
	6144:  _OutputFlag_name[51:57],
	8192:  _OutputFlag_name[57:62],
	16384: _OutputFlag_name[62:67],
	32768: _OutputFlag_name[67:72],
}

func (i OutputFlag) String() string {
	if str, ok := _OutputFlag_map[i]; ok {
		return str
	}
	return "OutputFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
